# Generated by Django 3.2.12 on 2022-11-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_issuebook_idate'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='rdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
